spring:
  application:
    name: demo

ollama:
  base-url: http://localhost:11434
  model: qwen3-vl:8b
  timeout: 60s

milvus:
  host: localhost
  port: 19530
  collection-name: aibrainbox_knowledge
  dimension: 4096 # 默认根据模型调整，qwen3-vl:8b 应该是 4096，或者 1024/1536，具体取决于模型层级



logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    reactor.netty.http.client: DEBUG
